1st Commit - Polymorphism
ReinisLubins/codelex-exercises pull request #10
Opened 2022-03-24 16:50 UTC by ReinisLubins

2022-04-21 17:43 UTC, NilsKula requested changes

2022-04-21 17:43 UTC, NilsKula commented on src/main/java/io/codelex/polymorphism/practice/exercise1/Audi.java
labāk izmanto override pie implementētām metodēm

2022-04-21 17:43 UTC, NilsKula commented on src/main/java/io/codelex/polymorphism/practice/exercise6/GetAnimal.java
> +            if (food[0].equals("Meat")) {
šo validāciju noteikti labāk būtu pašā Zebra klasē, jo tad jau vienmēr attieksies uz zebrām
zem `eat()` metodes

2022-04-21 17:43 UTC, NilsKula commented on src/main/java/io/codelex/polymorphism/practice/exercise6/GetAnimal.java
> +                Zebra zebra = new Zebra(inputParameters[1], "Cat",
typo

2022-04-21 21:25 UTC, ReinisLubins commented on src/main/java/io/codelex/polymorphism/practice/exercise1/Audi.java
Pārtaisiju un iepušoju. Pie metodem pieliku override, tikai nesaprotu kapēc interface metodem vaig override? Man likas, ka override liek tikai pie extended.

2022-04-22 08:03 UTC, NilsKula approved these changes

2022-04-22 12:39 UTC, merged