1st Commit - Java Advanced Test
ReinisLubins/codelex-exercises pull request #12
Opened 2022-04-01 17:56 UTC by ReinisLubins

2022-04-02 07:41 UTC, janistumpelis requested changes

2022-04-02 07:41 UTC, janistumpelis commented on src/main/java/io/codelex/advancedTest/Exercise1/CreditCard.java
> +        } catch (ArithmeticException e) {
kurā brīdī tiks mesta ArithmeticException kļūda? 🤔

2022-04-02 07:41 UTC, janistumpelis commented on src/main/java/io/codelex/advancedTest/Exercise1/Card.java
> +    public Card(String owner, String number, int ccvCode, double balance) {
Vajadzētu pielabot, ka visur tiek izmantots BigDecimal, nevis double

2022-04-02 07:41 UTC, janistumpelis commented on src/main/java/io/codelex/advancedTest/Exercise1/DebitCard.java
> +        } catch (ArithmeticException e) {
Tas pats šeit par to ArithmeticException..

2022-04-02 07:41 UTC, janistumpelis commented on src/main/java/io/codelex/advancedTest/Exercise2/Basket.java
> +public class Basket<T> {
Te bišķi tāds hibrīds sanācis. :D It kā izmanto generics T, bet tajā pašā laikā masīvs ir Object.. Mans ieteikums tomēr būtu pārtaisīt to Object[] par List<T> un tad tās kļūdas mest atkarībā no counter vērtības

2022-04-02 07:41 UTC, janistumpelis commented on src/main/java/io/codelex/advancedTest/Exercise2/Basket.java
> +            basket[counter] = item;
Man liekas, ka šis īsti nestrādā... Tu vienkārši masīva elementam piešķir jaunu vērtību, bet no masīva jau neko neizņem. Bet šis tiktu atrisināts, ja izmantotu Object[] vietā List<T> vai Stack<T>

2022-04-02 07:41 UTC, janistumpelis commented on src/main/java/io/codelex/advancedTest/Exercise2/Tests.java
> +        Basket<Object> basket1 = new Basket<>();
Šādam basket, Tu varētu pievienot, gan Apple, gan Mushroom, jo faktiski grozs saturēs objektus ;)

2022-04-02 07:41 UTC, janistumpelis commented on src/main/java/io/codelex/advancedTest/Exercise3/Joiner.java
> +        List<String> newList = Stream.of(objects).map(Object::toString).toList();
Šī pirmā rinda ļoti laba, tālāk gan var izmantot String.join metodi - iegooglē un paskaties ko tā dara.

2022-04-02 07:41 UTC, janistumpelis commented on src/main/java/io/codelex/advancedTest/Exercise4/Test.java
> +    public static void main(String[] args) throws FileNotFoundException {
Ir labi, tikai šis neapgriež faila nosaukumu otrādi - bet tas sīkums, vari atstāt, kā ir!

2022-04-02 07:41 UTC, janistumpelis commented on src/main/java/io/codelex/advancedTest/Exercise5/PartOf.java
> +        return null;
Nu te Tev izskatās, ka riktīgi maz pietrūka 👍 Vienīgi Predicate ari norādi tipu Predicate<T>

2022-04-02 07:41 UTC, janistumpelis commented
Man liekas kopumā ir tīri ok, tikai ir dažas lietas, kuras jāpielabo!

2022-04-02 08:54 UTC, ReinisLubins commented on src/main/java/io/codelex/advancedTest/Exercise1/Card.java
> +    public Card(String owner, String number, int ccvCode, double balance) {
Konstruktora uzrakstiju double, lai kad veidojot objektu būtu vieglāk ierakstīt. Pēc tam apakšā konstruktors konvertē uz Bigdecimal. Tā labāk nedarīt?

2022-05-01 12:26 UTC, janistumpelis approved these changes

2022-05-01 12:50 UTC, merged