Completed Tasks - "Flow Control and Loops"
ReinisLubins/codelex-exercises pull request #2
Opened 2022-02-27 18:43 UTC by ReinisLubins

2022-03-01 13:06 UTC, janistumpelis requested changes
Galvenais pārbaudi, kas ar to formatējumu, kāpēc pēc if figūriekavas liekās jaunā rindā.

2022-03-01 13:06 UTC, janistumpelis commented on src/main/java/io/codelex/flowcontrol/exercises/Exercise5.java
> +    public static void PhoneKeyPad(String inChar)
Metožu nosaukumiem jābūt camelCase.

2022-03-01 13:06 UTC, janistumpelis commented on src/main/java/io/codelex/flowcontrol/practice/LargestNumber.java
> +        {
Pamēģini pārformatēt kodu, figūriekavai jābūt uzreiz aiz IF nosacījuma nevis rindiņu zemāk. T.i.:
`if (num1 > num2 && num1 > num3) {`
Nevis :
```
if (num1 > num2 && num1 > num3) 
{
```

2022-03-01 13:06 UTC, janistumpelis commented on src/main/java/io/codelex/loops/exercises/Exercise10.java
> +    public static void NumberSquare()
Te tas pats par funkciju nosaukumiem, kuriem jābūt camelCase

2022-03-01 13:06 UTC, janistumpelis commented on src/main/java/io/codelex/loops/exercises/Exercise6.java
> +    public static void FizzBuzz(int inputInt)
Es vairāk par tiem metožu nosaukumiem nekomentēšu - vienkārši izlabo tad visur.

2022-03-01 13:06 UTC, janistumpelis commented on src/main/java/io/codelex/loops/exercises/Exercise7.java
> +        return (int)Math.floor(Math.random()*(diceMaxRange-diceMinRange+1)+diceMinRange);
Vai ir jēga rakstīt šo izteiksmi šādi:
`(diceMaxRange-diceMinRange+1)`
Ja faktiski ņemot vērā to, ka minRange = 1, tad sanāk, ka izteiksme ir vienāda ar sekojošo:
`(diceMaxRange)`

2022-03-01 13:06 UTC, janistumpelis commented on src/main/java/io/codelex/loops/exercises/Exercise7.java
> +        return (int)Math.floor(Math.random()*(diceMaxRange-diceMinRange+1)+diceMinRange);
Bet pluss par to, ka izmanto atsevišķu metodi priekš kauliņa mešanas.

2022-03-01 13:06 UTC, janistumpelis commented on src/main/java/io/codelex/loops/exercises/Exercise7.java
> +                    break;
Šis nav obligāti jālabo - bet iespējams break vietā jāizmanto gameOver mainīgais, ja reiz to izmanto citur, lai pateiktu, ka cikls jāpārtrauc.

2022-03-01 13:06 UTC, janistumpelis commented on src/main/java/io/codelex/loops/exercises/Exercise9.java
> +            int firstDice = rollTheDice(1, 6);
Īsti nav jēgas tos mainīgos tai metodei padot, ja reiz viņi nekad nemainās. Tad faktiski metodē vari viņus iekodēt, nevis padot.

2022-03-01 13:06 UTC, janistumpelis commented on src/main/java/io/codelex/loops/practice/MultiplyByItself.java
> +        //todo - complete loop to multiply i with itself n times, it is NOT allowed to use Math.pow()
Te gan bija domāts, ka mainīgais i jāreizina ar sevi n reizes t.i., piemēram, ja i = 10, un n tiek ievadīts 3, tad rezultātam jābūt 10 * 10 * 10, bet saprotu, ka tie nosacījumi nebija baigi skaidri, tāpēc var palikt.

2022-03-01 14:21 UTC, ReinisLubins commented on src/main/java/io/codelex/flowcontrol/exercises/Exercise5.java
> +    public static void PhoneKeyPad(String inChar)
Es veicu push un visu izlaboju. Vienigais exercise - piglet, camelCase aizmirsu apmainīt.

2022-03-14 18:41 UTC, janistumpelis approved these changes

2022-03-14 18:57 UTC, merged