Date and time exercises
ReinisLubins/codelex-exercises pull request #5
Opened 2022-03-11 09:38 UTC by ReinisLubins

2022-03-22 22:18 UTC, NilsKula requested changes
baigi labi

2022-03-22 22:18 UTC, NilsKula commented on src/main/java/io/codelex/practice/Exercise1/Date.java
> +    public static void hoursOfWork(LocalDate firstDate, LocalDate secondDate) { // logic
private

2022-03-22 22:18 UTC, NilsKula commented on src/main/java/io/codelex/practice/Exercise1/Date.java
> +            if (date.getDayOfWeek() == DayOfWeek.SATURDAY || date.getDayOfWeek() == DayOfWeek.SUNDAY) {
laba vieta palīgmetodei, piemēram, `if(isWeekend())`

2022-03-22 22:18 UTC, NilsKula commented on src/main/java/io/codelex/practice/Exercise1/Date.java
> +                sumOfHours += 8;
constant

2022-03-22 22:18 UTC, NilsKula commented on src/main/java/io/codelex/practice/Exercise2/Update.java
> +            if (date.getYear() == yearToUpdate && date.getMonthValue() == monthToUpdate) {
arī palīgmetodi

2022-03-22 22:18 UTC, NilsKula commented on src/main/java/io/codelex/practice/Exercise3/DatePeriod.java
> +        if (firstDate.isBefore(secondPeriod.firstDate) && secondDate.isAfter(secondPeriod.firstDate)) { // -_
arī čupiņu ar mazām palīgmetodēm

2022-03-23 09:43 UTC, ReinisLubins commented on src/main/java/io/codelex/practice/Exercise3/DatePeriod.java
> +        if (firstDate.isBefore(secondPeriod.firstDate) && secondDate.isAfter(secondPeriod.firstDate)) { // -_
Pievienoju mainīgos lai vieglāk saprastu loģiku, citas palīgmetodes nevarēju izdomāt.

2022-03-24 21:38 UTC, NilsKula approved these changes

2022-03-24 22:43 UTC, merged