1st Commit - Exceptions
ReinisLubins/codelex-exercises pull request #8
Opened 2022-03-21 20:51 UTC by ReinisLubins

2022-03-30 20:40 UTC, NilsKula requested changes

2022-03-30 20:40 UTC, NilsKula commented on src/main/java/io/codelex/exceptions/Exercise2.java
> +        } catch (ArithmeticException e) {
`After each try{} block put a catch{} block which catches the exception, prints a stack trace, and throws the exception object to its caller.`

2022-03-30 20:40 UTC, NilsKula commented on src/main/java/io/codelex/exceptions/Exercise4.java
> +class NonPositiveNumberException extends Exception {
kā nested class vai tad labāk atsevišķā failā

2022-04-13 13:25 UTC, NilsKula requested changes
izlabo to par jaunu izmešanu

2022-04-13 13:25 UTC, NilsKula commented on src/main/java/io/codelex/exceptions/Exercise2.java
> +            System.out.println("Exception object: " + e);
šeit jau atkal tu tik izprintē, bet neizmet pa jaunam, kas būtu `throw e`

2022-04-13 13:37 UTC, ReinisLubins commented on src/main/java/io/codelex/exceptions/Exercise2.java
> +            System.out.println("Exception object: " + e);
apmainiju ka izmet stacktrace un throw e.

2022-04-13 14:16 UTC, NilsKula approved these changes

2022-04-13 14:18 UTC, merged